### PR TITLE
Collapsing Sections

### PR DESCRIPTION
**Pull request by bernardlee**
The "Headers" and "Payload" text can be clicked to hide the bodies of the respective sections. For example, clicking "Headers" will change the text to "Headers ..." and hide all related elements. This can be useful for people who want more visibility in the Result area when it's at the bottom but don't use the Headers and/or Payload sections.

### CODE REVIEW

**Comment by ddavison** [comment]
almost there!

think we could get a couple things added to what you have?

1. Maybe color the "Headers" and "Payload" header to another color
2. Add `cursor: pointer;` to the styling of the headers; that way we know they are clickable
3. Add an arrow prefix. (`￫` for collapsed, and `￬` for expanded?)
4. Add a nice smooth transition for the collapsing and expanding

item number 4 is completely optional, but the rest i'd like done.  if you have time, you can do number 4 as well :)  purely cosmetic, but would be nice.

**Comment by ddavison** [comment]
there are a bunch of ASCII arrows [here](http://character-code.com/arrows-html-codes.php) that you could choose from.  whatever looks best :)

**Comment by bernardlee** [comment]
I can definitely do the first three things.  I'm not too experienced in working with animations but I'll try to add that in as well.

**Comment by ddavison** [comment]
cool! like i said, don't worry about it if it's taking too long :)

**Comment by ddavison** [comment]
I dig!  👍 

@javaguirre ?

**Comment by javaguirre** [comment]
I haven't checked the functionality, but I think It's a nice idea, so let's merge it if it's good to go! :-D

**Comment by bernardlee** [comment]
Thank you.  I'll work on the animation now.

**Pull request merged**
