### PR TITLE
Save load requests

### PR DESCRIPTION
**Pull request by javaguirre**
With this functionality we can save requests (100 for now, but this will be configurable in the future). We also have a recent requests feature where the most recent requests are stored.

@ddavison Can you check if It's working for you too?

Any opinion or criticism, here I am!

Note: the Unittests are passing, but sometimes there is some kind of timeout problem with Travis CI, we might need to change this configuration.

### CODE REVIEW

**Comment by javaguirre** [comment]
I fixed the method highlighting when loading requests, I think we're ready to merge, I'll try to fix the Travis environment this week.

@ddavison Please let me know if you find anything, otherwise we could merge and create a new version. :-)

**Comment by javaguirre** [comment]
I've spent some time on the Travis issue, but I haven't found how to fix It yet. I'll vote for merging the PR and create the new GIF for the Readme, I can do It if you're ok with It @ddavison.

**Comment by ddavison** [comment]
yea, sorry - i just got a new computer, so still customizing it, and getting all my workspaces back up ;)

**Comment by ddavison** [comment]
i'd also like to implement #30 in this branch

**Comment by ddavison** [comment]
going to push the new version now

**Comment by ddavison** [comment]
pushed as new major version.  1.0 finally :P

**Comment by javaguirre** [comment]
Veery nice! :-D

On Tue, Mar 15, 2016, 18:33 Dj <notifications@github.com> wrote:

> pushed as new major version. 1.0 finally :P
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ddavison/rest-client/pull/29#issuecomment-196938777>
>
-- 
—
Javier Aguirre
https://javaguirre.net

**Pull request merged**
