### PR TITLE
Refactor class/id interpolation

### PR DESCRIPTION
**Pull request by jonatanklosko**
I think that this decreases the complexity =)
Basically for both `class` and `id` there was `.split('.')[1]}` and `.split('#')[1]}` accordingly.
Now it's just a method all that removed the first character.
Maybe you will came up with a better name? =)

### CODE REVIEW

**Comment by ddavison** [comment]
i agree that the way i set this up originally is really stupid.. splitting on everything.  having this would make it readable.  thanks!  keep it up!

**Comment by jonatanklosko** [comment]
`name_of` is indeed nicer, I've updated the code.
Btw. is there any case convention? I see both camel and snake here.

**Comment by ddavison** [comment]
I think i'd prefer snake_case rather than camelCase in CoffeeScript.  i'll edit the CONTRIBUTING.md sometime to include that

**Comment by ddavison** [comment]
but you're right.. go ahead and do it camelCase since the other methods are that way

**Comment by jonatanklosko** [comment]
No problem it's just a quick replacement. I updated to camelCase, I hope that's what you wanted =)

**Comment by ddavison** [comment]
hey @jonatanklosko , could you rebase and fix the conflicts please? :)

**Comment by jonatanklosko** [comment]
Done!

**Pull request merged**
