### PR TITLE
Tab inserts tab

### PR DESCRIPTION
**Pull request by bernardlee**
I added a checkbox to enable the "tab inserts tab" option.  This will insert a tab character if the option is checked while the tab key is pressed within a textarea element.

### CODE REVIEW

**Comment by javaguirre** [comment]
Hi! I'd say this is [more a package config option](https://atom.io/docs/api/v1.2.0/Config) than an in app option.

**Comment by bernardlee** [comment]
Hello.  I can move it to the package configuration options if that's preferred.

**Comment by javaguirre** [comment]
I think it makes sense to have such an option, more comfortable when formatting json for example. :+1:

**Comment by bernardlee** [comment]
All right.  I'll close this and submit another pull request once I've moved the option.

**Comment by javaguirre** [comment]
Thank you!

**Pull request closed without merging**
