### PR TITLE
Json result format

### PR DESCRIPTION
**Pull request by javaguirre**
This is related to #10 

screen shot 2015-11-04 at 11 50 15

The format is good now, but the syntax highlighting is a bit trickier if trying to use Atom internal system, although I almost have It. I am using the grammar tokenizer for highlighting, but I am trying to get a method from Atom API to pass the tokens to html, It doesn't seem is there anymore, or I need to read more code. Now I have:

```coffeescript
grammar = atom.grammars.grammarForScopeName('source.json')
tokenizedLines = grammar.tokenizeLines(@processResult(body), undefined, 4))
```

I'll continue working on It.

I also refactored some constants, and I think all the json related code should go in a different file, I'll get into that.

### CODE REVIEW

**Comment by ddavison** [comment]
:+1:

**Comment by javaguirre** [comment]
Found a couple of bugs, missing quotes, the other was already there, and It's related to the load of the package and initalization, both fixed.

I am adding tests for the features I added, we could use that as our starting base for testing the rest of the package.

**Comment by javaguirre** [comment]
Added some specs to test the new json result process.

**Comment by javaguirre** [comment]
I added the travis-ci config too, It worked well! :tada: 

screen shot 2015-11-04 at 17 37 31

**Comment by ddavison** [comment]
you can go ahead and merge this if it's finished :)

i'll also see what i can do about allowing you to do `apm publish`'s as well

**Comment by javaguirre** [comment]
Great, I'll do It.

Thank you!

**Pull request merged**
