### PR TITLE
Configuration load / save

### PR DESCRIPTION
**Pull request by ajaxlex**
Added basic configuration save and load feature which serializes url, headers, user_agent, and payload into a json object and persists to user specified file, and allows loading of same.

includes load and save buttons in ui

includes requirements for remote and dialog

### CODE REVIEW

**Comment by ajaxlex** [comment]
Oops - looks like a copy of the write block made it into lines 207-214

**Comment by ddavison** [comment]
thanks for spending some of your time to improve this plugin!  

give me a bit to see how this works, and more importantly, *if* it works :wink: 

stay tuned!

**Comment by ajaxlex** [comment]
Ok - my use case was limited ... I see I should have captured the method and content type information as well.  I can add these shortly.

**Comment by javaguirre** [comment]
Hi!

nice idea! I'd really use It too, but I think It would be better to have this functionality separated from the view as a class adding functionality.

I'm gonna check how It's done and see if I could contribute to this implementation. :-)

**Comment by javaguirre** [comment]
Hi!

I've been checking out how the save/load works, but there some errors I had to fix first.

You need to use Atom dialog as a requirement.

```coffee
dialog = require 'dialog'
```

You don't need to use the npm module dialog, It's not needed as a dependency.

I continue with It. :-)

Thank you for the PR!

**Comment by javaguirre** [comment]
Ok, I got It working with some changes, I see right now It only saves one request, which is not very useful.

I think we could squash the commits, refactor and make a new PR with all your changes and test the functionality. I'm on It.

**Comment by javaguirre** [comment]
I think the best would be to have a list of json objects with all our saved requests in a file, and load that, maybe even there is no need to select which file to load, although It could be an option we could set for the package, what do you think @ddavison ?

**Comment by ddavison** [comment]
well - intellij mocks this same behavior and allows an export/import system as well.  They store it in specific files that the user saves.  we could do this.

conversely, having all requests saved in one file, and allowing you to load them one by one would also be extremely helpful as we can actually create palette items for each saved item.  I like that idea.

**Comment by ddavison** [comment]
Something like:

<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> -> `Rest Client: Load GitHub API Test Request`

So we'd be able to load any config that is saved in some json file.

**Comment by ddavison** [comment]
looking back though - i did a terrible job on this codebase :(  i put everything in the view.. shame.. sorry about that @javaguirre

**Comment by javaguirre** [comment]
Yes, I think is a nice idea. I was thinking on having a json structure such as:

```json
{
  "default": [
    { "method": "GET", "url": "https://example.com" },
    ...
  ],
  "github" : [
     ... requests json objects ...
   ]
}
```
We could start saving only requests in the `default` group, but this structure will allow us to have different `groups` in the future, that's very handy.

Once we have the logic to do this, we can also decide if we want the package to be able to export the file to a different location and so on, I think we can keep that, but I would give It less protagonism in the GUI, we can talk about It later too.

We could bind that behaviour to an action inside the package (`Rest Client: Load GitHub API Test Request` as you said) once It's done too.

Don't worry about the code, we are improving It with tests, so refactoring will not be painful. :-)

**Comment by ddavison** [comment]
what would grouping allow?

I was thinking something like:

```json
[
  "github-api-test": {
    "name": "GitHub API Test",
    "url": "https://api.github.com",
    "method": "GET",
    "payload": "",
    "headers": [
        
    ]
  }
]
```

**Comment by javaguirre** [comment]
I have requests for different projects, so instead of having all the requests in a list, we could have a first layer of group names so we can group requests (per project for example) if we want. This is also possible using a file per project and importing/exporting, but I find that much more messy. 

I came up with the idea seeing [Postman for Chrome][postman], postman has collections, which will be the equivalency of what I want to achieve in the future. It's just a way of organizing your requests better when you start having more than a few.

[postman]: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

**Comment by ddavison** [comment]
ohhh i see, that makes sense.  i like it. :+1:

**Comment by javaguirre** [comment]
Great! I am playing with It, I'll send you an example soon. :-)

**Comment by javaguirre** [comment]
I am refactoring a bit before doing this, I have created a class to open the file in the editor, so we have that logic outside the view, and also everything related to the request, I am adding tests too to these parts, It's easier to test and build the following features this way IMO.

**Comment by ddavison** [comment]
you're amazing.  :tada: :star2:

**Comment by ddavison** [comment]
hey @javaguirre, go to https://atom.io/account and make sure you have an api token.

**Comment by javaguirre** [comment]
@ddavison I have one, I have three themes published :-)

**Comment by ddavison** [comment]
ok.. well, so you're able to `apm publish`, in the fact that you can push a TAG, but can you push to the package repo?  i'm not sure.. still working on that.

**Comment by javaguirre** [comment]
Nice, thank you!

I can push to `ddavison/rest-client`, I am just doing It in my fork until I have something clean, when the feature is clean I make the PR so we have a PR history in the repo.

I could do everything inside this repo instead of my fork, but I think we could separate the main package branches from the features this way, I don't know, I think both options (pushing here or in my fork while creating a new feature) are valid options.

**Comment by ddavison** [comment]
i dont mind if you use this one, just put it as a feature branch :)

**Comment by javaguirre** [comment]
Ok, I am working now [here][branch], I'll create the next one in this repo.

[branch]: https://github.com/javaguirre/rest-client/tree/http-refactor

**Comment by ddavison** [comment]
i guess you can:  https://discuss.atom.io/t/how-can-i-allow-another-user-to-publish-to-my-package/22453/2?u=ddavison

**Comment by javaguirre** [comment]
That's comfortable, I think we can create a new minor version when we have the save/load requests feature. Right now I've been mostly refactoring, so the user won't see any changes.

**Comment by yesnault** [comment]
+1 I hope so see this great feature soon :)

**Comment by javaguirre** [comment]
I'll try to finish It before the end of the month. It's a work in progress in `save-load-requests`.

**Comment by javaguirre** [comment]
@ddavison It's starting to go somewhere :-)

Could you please check It out and give me your feedback? I don't like the way It looks, but I need a fresh view, the branch is [save-load-requests](https://github.com/ddavison/rest-client/tree/save-load-requests).

Thank you!

**Comment by ddavison** [comment]
@javaguirre can this be closed out now?

**Comment by javaguirre** [comment]
Yes!

**Pull request closed without merging**
